from datetime import date
from typing import Optional, Protocol


class UserRepository(Protocol):
    async def get_by_email(self, email: str) -> Optional[dict]: ...
    async def get_by_id(self, user_id: str) -> Optional[dict]: ...
    async def create(self, user: dict) -> dict: ...


class MealEntryRepository(Protocol):
    async def create(self, entry: dict) -> dict: ...
    async def list_for_day(self, user_id: str, day: date) -> list[dict]: ...
    async def get(self, user_id: str, entry_id: str) -> Optional[dict]: ...
    async def update(self, user_id: str, entry_id: str, updates: dict) -> Optional[dict]: ...
    async def delete(self, user_id: str, entry_id: str) -> bool: ...


class FoodRepository(Protocol):
    async def search(self, query: str) -> list[dict]: ...
    async def get(self, food_id: str) -> Optional[dict]: ...
