from datetime import date
from typing import Optional, Protocol


class UserRepository(Protocol):
    async def get_by_email(self, email: str) -> Optional[dict]: ...
    async def get_by_id(self, user_id: str) -> Optional[dict]: ...
    async def create(self, user: dict) -> dict: ...


class MealEntryRepository(Protocol):
    async def create(self, entry: dict) -> dict: ...
    async def list_for_day(self, user_id: str, day: date) -> list[dict]: ...
    async def get(self, user_id: str, entry_id: str) -> Optional[dict]: ...
    async def update(self, user_id: str, entry_id: str, updates: dict) -> Optional[dict]: ...
    async def delete(self, user_id: str, entry_id: str) -> bool: ...


class FoodRepository(Protocol):
    async def search(self, query: str) -> list[dict]: ...
    async def get(self, food_id: str) -> Optional[dict]: ...


class WorkoutRepository(Protocol):
    async def create(self, workout: dict) -> dict: ...
    async def list_for_user(self, user_id: str, workout_type: Optional[str] = None) -> list[dict]: ...
    async def get(self, user_id: str, workout_id: str) -> Optional[dict]: ...
    async def update(self, user_id: str, workout_id: str, updates: dict) -> Optional[dict]: ...
    async def delete(self, user_id: str, workout_id: str) -> bool: ...


class ExerciseRepository(Protocol):
    async def search(self, query: str) -> list[dict]: ...
    async def get(self, exercise_id: str) -> Optional[dict]: ...
    async def create(self, exercise: dict) -> dict: ...


class MoodEntryRepository(Protocol):
    async def create(self, entry: dict) -> dict: ...
    async def list_for_user(
        self, user_id: str, start: Optional[date] = None, end: Optional[date] = None
    ) -> list[dict]: ...
    async def get(self, user_id: str, entry_id: str) -> Optional[dict]: ...
    async def update(self, user_id: str, entry_id: str, updates: dict) -> Optional[dict]: ...
    async def delete(self, user_id: str, entry_id: str) -> bool: ...


class JournalEntryRepository(Protocol):
    async def create(self, entry: dict) -> dict: ...
    async def list_for_user(self, user_id: str) -> list[dict]: ...
    async def get(self, user_id: str, entry_id: str) -> Optional[dict]: ...
    async def update(self, user_id: str, entry_id: str, updates: dict) -> Optional[dict]: ...
    async def delete(self, user_id: str, entry_id: str) -> bool: ...
